// svelte/src/components/Timeline/ProjectCard/ProjectCardActions.svelte
<!--
  @component

  A project's demo and source links.
-->
<script lang="ts">
  import { type Project } from 'shared';
  import TextButton from '../../TextButton.svelte';

  const { project }: { project: Project } = $props();
</script>

<div class="links">
  {#if project.demoLink}
    <TextButton text="demo" url={project.demoLink} />
  {/if}
  <TextButton text="source" url={project.codeLink} />
</div>

<style>
  .links {
    display: flex;
    gap: var(--standard-spacing);
  }
</style>

// react/app/components/Timeline/ProjectCard/ProjectCardActions.tsx
import { type Project } from 'shared';
import TextButton from '../../TextButton';
import styles from './ProjectCardActions.module.css';

/**
 * A project's demo and source links.
 */
export default function ProjectCardActions({ project }: { project: Project }) {
  return (
    <div className={styles.links}>
      {project.demoLink ? <TextButton text="demo" url={project.demoLink} /> : null}
      <TextButton text="source" url={project.codeLink} />
    </div>
  );
}
