// svelte/src/components/Projects/Projects.svelte
<script lang="ts">
  import projects from 'config/projects';
  import CardGrid from '../CardGrid.svelte';
  import ProjectCard from './ProjectCard.svelte';
</script>

<div class="container">
  <CardGrid>
    {#each projects as project (project.name)}
      <ProjectCard
        projectName={project.name}
        imgUrl={project.thumbnailUrl}
        imgAlt={project.thumbnailDescription}
        info={project.info}
        demoLink={project.demoLink}
        codeLink={project.codeLink}
      />
    {/each}
  </CardGrid>
</div>

<style>
  .container {
    display: flex;
    justify-content: center;
  }
</style>

// react/app/components/Projects/Projects.tsx
import projectImages from '$lib/projectImages';
import projects, { type ProjectKey } from '$shared/config/projects';
import CardGrid from '../CardGrid';
import Project from './Project';
import styles from './Projects.module.css';

export default function Projects() {
  return (
    <section id="projects" className={styles.container}>
      <CardGrid>
        {Object.entries(projects).map(([key, card]) => (
          <Project
            key={card.name}
            title={card.heading}
            info={card.info}
            imgSrc={projectImages[key as ProjectKey]}
            imgAlt={card.thumbnailDescription}
            demoLink={card.demoLink}
            codeLink={card.codeLink}
          />
        ))}
      </CardGrid>
    </section>
  );
}
