// components/Footer.tsx
import React from 'react';
import {
  Typography,
  Theme,
  Link,
} from '@material-ui/core';
import { makeStyles } from '@material-ui/styles';

const useStyles = makeStyles((theme: Theme) => ({
  footer: {
    backgroundColor: theme.palette.background.paper,
    padding: theme.spacing(6),
  },
}));

export default function Footer(): JSX.Element {
  const classes = useStyles();
  return (
    <footer className={classes.footer}>
      <Typography variant="h6" align="center" gutterBottom>
        See the code for this website
        {' '}
        <Link
          href="https://github.com/aneuhold/portfolio"
          rel="noopener noreferrer"
          target="_blank"
          color="primary"
        >
          here!
        </Link>
      </Typography>
      <Typography variant="subtitle1" align="center" color="textSecondary" component="p">
        ©
        {(new Date()).getFullYear()}
        {' '}
        Anton Neuhold
      </Typography>
    </footer>
  );
}

// svelte/src/components/Footer.svelte
<template>
  <footer>
    <span class="header-6"
      >See the code for this website
      <a href="https://github.com/aneuhold/portfolio" rel="noopener noreferrer" target="_blank"
        >here!</a
      >
    </span>
    <span class="subtitle-1">©{new Date().getFullYear()} Anton Neuhold</span>
  </footer>
</template>

<style lang="scss">
  @use '../global-styles/theme.scss';

  footer {
    background-color: theme.$background;
    padding: calc(theme.$standard-spacing * 6);
    display: flex;
    flex-direction: column;
    align-items: center;
  }
</style>
