// react/app/components/Link.tsx
import styles from './Link.module.css';

export default function Link({
  url,
  linkText,
  ariaLabel
}: {
  url: string;
  linkText: string;
  ariaLabel: string;
}) {
  return (
    <a
      rel="noopener noreferrer"
      target="_blank"
      href={url}
      aria-label={ariaLabel}
      className={styles.link}
    >
      {linkText}
    </a>
  );
}

// svelte/src/components/Link.svelte
<script lang="ts">
  export let url: string;
  export let linkText: string;
</script>

<a rel="noopener noreferrer" target="_blank" href={url}>{linkText}</a>

<style>
  a {
    color: var(--color-primary);
    text-decoration-color: var(--color-primary-300);
  }

  a:hover {
    text-decoration-color: var(--color-primary);
  }
</style>
