// svelte/src/components/TextButton.svelte
<script lang="ts">
  export let text: string;
  export let url: string;
</script>

<a rel="noopener noreferrer" target="_blank" class="button-text" href={url}>
  {text}
</a>

<style>
  a {
    display: flex;
    flex-direction: row;
    padding: 4px 5px;
    border-radius: calc(var(--standard-spacing) / 2);
    text-decoration: none;
    justify-content: center;
    min-width: 64px;
    color: var(--color-primary);
  }

  a:hover {
    background-color: var(--color-primary-100);
  }
</style>

// react/app/components/TextButton.tsx
import styles from './TextButton.module.css';

export default function TextButton({ url, text }: { url: string; text: string }) {
  return (
    <a
      className={`button-text ${styles.button}`}
      href={url}
      target="_blank"
      rel="noopener noreferrer"
    >
      {text}
    </a>
  );
}
